# Generated by Django 3.2.6 on 2021-08-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.CharField(default='No Description', max_length=255),
            preserve_default=False,
        ),
    ]
